name: ARSketchTracer
options:
  deploymentTarget:
    iOS: "16.0"
settings:
  BASE_SDK: iphoneos
  DEVELOPMENT_TEAM: ""
  SWIFT_VERSION: "5.9"
packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    majorVersion: 2.5.1
targets:
  ARSketchTracer:
    type: application
    platform: iOS
    sources:
      - path: ARSketchTracer
      - path: DesignSystem
      - path: Features
      - path: Models
      - path: Resources
      - path: Utils
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.arsketchtracer
      INFOPLIST_FILE: Info.plist
      TARGETED_DEVICE_FAMILY: "1"
    prebuildScripts: []
    postbuildScripts: []
    dependencies:
      - package: Supabase
        product: Supabase
      - sdk: ARKit.framework
      - sdk: RealityKit.framework
